name 'attachmentgenie-motd'
version '1.1.0'

author 'Bram Vogelaar'
license 'Apache License 2.0'
project_page 'https://github.com/attachmentgenie/puppet-motd'
source 'git://github.com/attachmentgenie/puppet-motd.git'
summary 'Puppet motd Module'
description 'Module for configuring motd. Currently we just used the puppetlabs/concat example.'
dependency 'puppetlabs/stdlib', '>=2.2.1'
dependency 'puppetlabs-concat', '>=1.0.0'
